### ISSUE TITLE
delete or edit a todo

### ISSUE THREAD

**Issue by fmkarakus** [gelilaa/project#3]
The user will be able to edit or delete a todo from the list.
- [ ] developed in the separate branch
- [ ] added delete and edit buttons
- [ ] create `deleteOne` and ` edit` functions
